In [1]:
import pandas as pd
import os
import joblib

pd.set_option('future.no_silent_downcasting', True)

In [2]:
import requests

API_KEY = "0943842962317c345fa1bc34ac6486ea"   # PI key

def get_weather(city, date):
    try:
        url = f"https://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)
        data = response.json()

        # DEBUG (optional)
        # print(data)

        if "list" not in data:
            return "Unknown"

        for item in data["list"]:
            if date in item["dt_txt"]:
                return item["weather"][0]["main"]

        return "Clear"   # fallback

    except:
        return "Unknown"

In [3]:
df = pd.read_csv("../artifacts/Ground_clean_dataset.csv")
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [4]:
bookings = pd.read_csv("../artifacts/bookings.csv")

In [5]:
model = joblib.load("../artifacts/rf_model.joblib")
scaler = joblib.load("../artifacts/scaler.joblib")
model_features = joblib.load("../artifacts/model_features1.joblib")

In [6]:
import pandas as pd

team_stats = pd.read_csv("../artifacts/team_stats.csv")

team_stats

,team_name,ground_name,matches_played_,wins,matches_played
0,Royal College XI,SSC Cricket Ground,NaN,7,10.0
1,Royal College XI,NCC Cricket Ground,NaN,5,8.0
2,Royal College XI,Colombo Colts Ground,NaN,4,7.0
3,Royal College XI,Colombo City Cricket Park,NaN,3,6.0
4,Royal College XI,P Sara Oval Ground,NaN,3,6.0
...,...,...,...,...,...
506,Panadura SC,De Soysa Stadium,NaN,3,7.0
507,Panadura SC,SSC Cricket Ground,NaN,2,6.0
508,Panadura SC,NCC Cricket Ground,NaN,1,5.0
509,Panadura SC,Colombo Colts Ground,NaN,2,5.0
510,Panadura SC,P Sara Oval Ground,NaN,2,6.0

In [7]:
new_data = pd.DataFrame([
# Royal College XI
["Royal College XI","SSC Cricket Ground",10,7],
["Royal College XI","NCC Cricket Ground",8,5],
["Royal College XI","Colombo Colts Ground",7,4],
["Royal College XI","Colombo City Cricket Park",6,3],
["Royal College XI","P Sara Oval Ground",6,3],
["Royal College XI","Bloomfield Cricket Ground",5,2],
["Royal College XI","De Soysa Stadium",5,2],
["Royal College XI","Panadura Public Ground",4,1],

# St Joseph's
["St. Joseph's College XI","SSC Cricket Ground",10,7],
["St. Joseph's College XI","NCC Cricket Ground",8,4],
["St. Joseph's College XI","Colombo City Cricket Park",7,3],
["St. Joseph's College XI","Colombo Colts Ground",6,2],
["St. Joseph's College XI","P Sara Oval Ground",7,3],
["St. Joseph's College XI","Bloomfield Cricket Ground",6,2],
["St. Joseph's College XI","De Soysa Stadium",6,2],

# Ananda College XI
["Ananda College XI","SSC Cricket Ground",9,5],
["Ananda College XI","NCC Cricket Ground",7,3],
["Ananda College XI","Colombo Colts Ground",8,4],
["Ananda College XI","Colombo City Cricket Park",7,3],
["Ananda College XI","P Sara Oval Ground",7,3],
["Ananda College XI","Bloomfield Cricket Ground",6,2],
["Ananda College XI","De Soysa Stadium",5,2],
["Ananda College XI","Panadura Public Ground",4,1],

# Nalanda College XI
["Nalanda College XI","SSC Cricket Ground",8,4],
["Nalanda College XI","NCC Cricket Ground",7,3],
["Nalanda College XI","Colombo Colts Ground",9,5],
["Nalanda College XI","Colombo City Cricket Park",6,2],
["Nalanda College XI","P Sara Oval Ground",7,3],
["Nalanda College XI","Bloomfield Cricket Ground",6,2],
["Nalanda College XI","De Soysa Stadium",5,2],

# St Peter's
["St. Peter's College XI","SSC Cricket Ground",7,3],
["St. Peter's College XI","NCC Cricket Ground",6,2],
["St. Peter's College XI","Colombo Colts Ground",8,4],
["St. Peter's College XI","Colombo City Cricket Park",7,3],
["St. Peter's College XI","Bloomfield Cricket Ground",6,2],
["St. Peter's College XI","P Sara Oval Ground",6,2],

# Colombo CC
["Colombo CC","SSC Cricket Ground",12,9],
["Colombo CC","NCC Cricket Ground",10,7],
["Colombo CC","Colombo Colts Ground",9,6],
["Colombo CC","P Sara Oval Ground",8,5],
["Colombo CC","Bloomfield Cricket Ground",7,4],
["Colombo CC","De Soysa Stadium",8,5],
["Colombo CC","Panadura Public Ground",7,3],
["Colombo CC","Kalutara Public Ground",6,2],

# Sinhalese SC
["Sinhalese SC","SSC Cricket Ground",15,12],
["Sinhalese SC","NCC Cricket Ground",12,8],
["Sinhalese SC","Colombo Colts Ground",10,7],
["Sinhalese SC","P Sara Oval Ground",9,6],
["Sinhalese SC","Bloomfield Cricket Ground",8,5],
["Sinhalese SC","De Soysa Stadium",9,6],
["Sinhalese SC","Panadura Public Ground",8,4],
["Sinhalese SC","Kalutara Public Ground",7,3],

# NCC Club
["NCC Club","NCC Cricket Ground",14,10],
["NCC Club","SSC Cricket Ground",10,6],
["NCC Club","Colombo Colts Ground",9,5],
["NCC Club","P Sara Oval Ground",9,5],
["NCC Club","Bloomfield Cricket Ground",8,4],
["NCC Club","De Soysa Stadium",7,3],
["NCC Club","Panadura Public Ground",6,2],

# Moratuwa SC
["Moratuwa SC","De Soysa Stadium",10,7],
["Moratuwa SC","Moratuwa University Ground",6,3],
["Moratuwa SC","Kalutara Public Ground",8,4],
["Moratuwa SC","Panadura Public Ground",7,3],
["Moratuwa SC","SSC Cricket Ground",6,3],
["Moratuwa SC","NCC Cricket Ground",5,2],
["Moratuwa SC","Colombo Colts Ground",5,2],

# Panadura SC
["Panadura SC","Panadura Public Ground",10,6],
["Panadura SC","Kalutara Public Ground",8,3],
["Panadura SC","De Soysa Stadium",7,3],
["Panadura SC","SSC Cricket Ground",6,2],
["Panadura SC","NCC Cricket Ground",5,1],
["Panadura SC","Colombo Colts Ground",5,2],
["Panadura SC","P Sara Oval Ground",6,2]

], columns=["team_name","ground_name","matches_played","wins"])

In [8]:
team_stats

,team_name,ground_name,matches_played_,wins,matches_played
0,Royal College XI,SSC Cricket Ground,NaN,7,10.0
1,Royal College XI,NCC Cricket Ground,NaN,5,8.0
2,Royal College XI,Colombo Colts Ground,NaN,4,7.0
3,Royal College XI,Colombo City Cricket Park,NaN,3,6.0
4,Royal College XI,P Sara Oval Ground,NaN,3,6.0
...,...,...,...,...,...
506,Panadura SC,De Soysa Stadium,NaN,3,7.0
507,Panadura SC,SSC Cricket Ground,NaN,2,6.0
508,Panadura SC,NCC Cricket Ground,NaN,1,5.0
509,Panadura SC,Colombo Colts Ground,NaN,2,5.0
510,Panadura SC,P Sara Oval Ground,NaN,2,6.0

In [9]:
file_path = "../artifacts/team_stats.csv"
team_stats = pd.concat([team_stats, new_data], ignore_index=True)
team_stats.to_csv(file_path, index=False)

In [10]:
team_stats

,team_name,ground_name,matches_played_,wins,matches_played
0,Royal College XI,SSC Cricket Ground,NaN,7,10.0
1,Royal College XI,NCC Cricket Ground,NaN,5,8.0
2,Royal College XI,Colombo Colts Ground,NaN,4,7.0
3,Royal College XI,Colombo City Cricket Park,NaN,3,6.0
4,Royal College XI,P Sara Oval Ground,NaN,3,6.0
...,...,...,...,...,...
579,Panadura SC,De Soysa Stadium,NaN,3,7.0
580,Panadura SC,SSC Cricket Ground,NaN,2,6.0
581,Panadura SC,NCC Cricket Ground,NaN,1,5.0
582,Panadura SC,Colombo Colts Ground,NaN,2,5.0
583,Panadura SC,P Sara Oval Ground,NaN,2,6.0

In [11]:
def recommend_grounds(user_features, date, team_name=None, city=None, top_n=5):

    data = df.copy()

    #  Filter by city
    if city:
        data = data[data["city"].str.lower() == city.lower()]

    #  Team performance logic
    if team_name:
        team_data = team_stats[team_stats["team_name"] == team_name].copy()

        team_data["win_rate"] = team_data["wins"] / team_data["matches_played"]

        data = data.merge(team_data, on="ground_name", how="left")

        data["win_rate"] = data["win_rate"].fillna(0).astype(float)
        data["matches_played"] = data["matches_played"].fillna(0).astype(float)

        data = data.drop_duplicates(subset=["ground_name"])

    else:
        data["win_rate"] = 0

    #  weather column
    data["weather"] = data["city"].apply(lambda x: get_weather(x, date))

    #  Weather scoring function 
    def weather_score(condition):
        condition = str(condition).lower()
        if "rain" in condition or "storm" in condition:
            return 0
        elif "cloud" in condition:
            return 0.7
        else:
            return 1

    data["weather_score"] = data["weather"].apply(weather_score)

    # Remove booked grounds
    if not bookings.empty:
        booked = bookings[bookings["date"] == date]["ground_name"]
        data = data[~data["ground_name"].isin(booked)]


    # ML SCORING
    

    categorical_cols = ["city", "district", "province", "ground_type", "pitch"]

    # Encode full dataset
    data_encoded = pd.get_dummies(data, columns=categorical_cols)

    # Align with trained model features
    data_encoded = data_encoded.reindex(columns=model_features, fill_value=0)

    # Convert to numeric
    data_encoded = data_encoded.apply(pd.to_numeric, errors='coerce').fillna(0)

    # Scale
    X_scaled = scaler.transform(data_encoded)

    # Predict
    scores = model.predict_proba(X_scaled)[:, 1]

    # Assign ML score
    data["ml_score"] = scores

    # Final hybrid score (WITH WEATHER)
    data["final_score"] = (
        data["ml_score"] * 0.4 +
        data["win_rate"] * 0.4 +
        data["weather_score"] * 0.2
    )

    # Return top results
    return data.sort_values(by="final_score", ascending=False).head(top_n)

In [12]:
# Step 1: define input
user_input = {
    "price_(lkr)": 120000,
    "lights": 1,
    "parking": 1,
    "rating": 4
}

# Step 2: call function
result = recommend_grounds(
    user_input,
    date="2026-04-10",
    team_name="Royal College XI",
    city="colombo"
)

# step 3: output
top = result.iloc[0]
alt = result.iloc[1]

print("Ground Recommendation Result\n")

print("Best Match:")
print(f"{top['ground_name']} | Weather: {top['weather']}")

if "rain" in str(top["weather"]).lower():
    print("\n Not suitable due to bad weather")

    print("\n Alternative:")
    print(f"{alt['ground_name']} | Weather: {alt['weather']}")
else:
    print("\n Suitable for play")

Ground Recommendation Result

Best Match:
Colombo City Cricket Park | Weather: Clear

 Suitable for play

In [13]:
top = result.iloc[0]
alt = result.iloc[1] if len(result) > 1 else None

print("Ground Recommendation Result\n")

# Best Match
print("⭐ Best for Match:")
print(f"Ground: {top['ground_name']}")
print(f"ML Score: {top['ml_score']:.2f}")
print(f"Win Rate: {top['win_rate']:.2f}")
print(f"Final Score: {top['final_score']:.2f}")
print(f"Weather: {top['weather']}")

# Weather check
if "rain" in str(top["weather"]).lower() or "storm" in str(top["weather"]).lower():

    print("\n Warning:")
    print("This ground is not suitable due to bad weather.")

    if alt is not None:
        print("\n Recommended Alternative:")
        print(f"Ground: {alt['ground_name']}")
        print(f"ML Score: {alt['ml_score']:.2f}")
        print(f"Win Rate: {alt['win_rate']:.2f}")
        print(f"Final Score: {alt['final_score']:.2f}")
        print(f"Weather: {alt['weather']}")

        print("\n Reason:")
        print("Better weather conditions for playing.")

else:
    print("\n This ground is suitable for play.")

Ground Recommendation Result

⭐ Best for Match:
Ground: Colombo City Cricket Park
ML Score: 0.57
Win Rate: 0.50
Final Score: 0.63
Weather: Clear

 This ground is suitable for play.

In [14]:
top = result.iloc[0]
alt = result.iloc[1]

print(" Ground Recommendation Result\n")

print(" Best Match:")
print(f"{top['ground_name']} | Weather: {top['weather']}")

if "rain" in str(top["weather"]).lower():
    print("\n Not suitable due to bad weather")

    print("\n Alternative:")
    print(f"{alt['ground_name']} | Weather: {alt['weather']}")
else:
    print("\n Suitable for play")

 Ground Recommendation Result

 Best Match:
Colombo City Cricket Park | Weather: Clear

 Suitable for play

In [15]:
city="colombo"
date="2026-04-10"

In [16]:
top = result.iloc[0]
alt = result.iloc[1] if len(result) > 1 else None

print(" Ground Recommendation Result\n")

print(" Best Match:")
print(f"Ground: {top['ground_name']}")
print(f"ML Score: {top['ml_score']:.2f}")
print(f"Win Rate: {top['win_rate']:.2f}")
print(f"Final Score: {top['final_score']:.2f}")
print(f"Weather: {top['weather']}")

if "rain" in str(top["weather"]).lower():
    print("\n Warning:")
    print("This ground is not suitable due to bad weather.")

    if alt is not None:
        print("\n Recommended Alternative:")
        print(f"Ground: {alt['ground_name']}")
else:
    print("\n This ground is suitable for play.")

 Ground Recommendation Result

 Best Match:
Ground: Colombo City Cricket Park
ML Score: 0.57
Win Rate: 0.50
Final Score: 0.63
Weather: Clear

 This ground is suitable for play.

In [19]:
def recommend_and_book(result, city, date):
    import pandas as pd
    import os

    # Get top and alternative
    top = result.iloc[0]
    alt = result.iloc[1] if len(result) > 1 else None

    print("\n🏏 Ground Recommendation Result\n")

    print("🌟 Best Match:")
    print(f"Ground: {top['ground_name']}")
    print(f"ML Score: {top['ml_score']:.2f}")
    print(f"Win Rate: {top['win_rate']:.2f}")
    print(f"Final Score: {top['final_score']:.2f}")
    print(f"Weather: {top['weather']}")

    # Weather check
    if "rain" in str(top["weather"]).lower():
        print("\n⚠️ Warning: This ground is not suitable due to bad weather.")

        if alt is not None:
            print("\n🔁 Recommended Alternative:")
            print(f"Ground: {alt['ground_name']}")
    else:
        print("\n✅ This ground is suitable for play.")

    # ---------------- BOOKING PART ----------------
    choice = input("\nDo you want to book this ground? (yes/no): ").strip().lower()

    if choice == "yes":
        file_path = "artifacts/bookings.csv"
        os.makedirs("artifacts", exist_ok=True)

        # Ask team name
        team_name = input("Enter team name: ")

        # Create booking record
        new_booking = {
            "ground_name": top["ground_name"],
            "date": date,
            "booked_by": team_name
        }

        new_df = pd.DataFrame([new_booking])

        # Check if file exists
        if os.path.exists(file_path):
            existing_df = pd.read_csv(file_path)

            # 🚫 Prevent duplicate booking
            if ((existing_df["ground_name"] == top["ground_name"]) & 
                (existing_df["date"] == date)).any():
                print("\n⚠️ This ground is already booked for this date!")
                return

            # Append
            new_df.to_csv(file_path, mode='a', header=False, index=False)
        else:
            new_df.to_csv(file_path, index=False)

        print("\n✅ Booking confirmed and saved!")

    elif choice == "no":
        print("\n❌ Booking cancelled.")

    else:
        print("\n⚠️ Invalid input. Please type 'yes' or 'no'.")

In [20]:
# ===== TEST INPUT =====
city = "Colombo"          # or any city in your dataset
date = "2026-03-25"       # format: YYYY-MM-DD

team_name = "Colombo CC"      # 🔥 give a team name OR set None
# team_name = None        # <- use this if you want to test without team

user_features = {
    "price_(lkr)": 120000,
    "rating": 4.5
}

# ===== RUN RECOMMENDATION =====
result = recommend_grounds(
    user_features=user_features,
    date=date,
    team_name=team_name,
    city=city,
    top_n=5
)

# ===== SHOW + BOOK =====
recommend_and_book(result, city, date)

🏏 Ground Recommendation Result

🌟 Best Match:
Ground: NCC Cricket Ground
ML Score: 0.56
Win Rate: 0.70
Final Score: 0.65
Weather: Clouds

✅ This ground is suitable for play.

Do you want to book this ground? (yes/no):  yes
Enter team name:  colombo cc

✅ Booking confirmed and saved!

In [21]:
def recommend_and_book(result, city, date):
    import pandas as pd
    import os

    # Get top and alternative
    top = result.iloc[0]
    alt = result.iloc[1] if len(result) > 1 else None

    print("\n🏏 Ground Recommendation Result\n")

    print("🌟 Best Match:")
    print(f"Ground: {top['ground_name']}")
    print(f"ML Score: {top['ml_score']:.2f}")
    print(f"Win Rate: {top['win_rate']:.2f}")
    print(f"Final Score: {top['final_score']:.2f}")
    print(f"Weather: {top['weather']}")

    # Weather check
    if "rain" in str(top["weather"]).lower():
        print("\n⚠️ Warning: This ground is not suitable due to bad weather.")

        if alt is not None:
            print("\n🔁 Recommended Alternative:")
            print(f"Ground: {alt['ground_name']}")
    else:
        print("\n✅ This ground is suitable for play.")

    # ---------------- BOOKING PART ----------------
    choice = input("\nDo you want to book this ground? (yes/no): ").strip().lower()

    if choice == "yes":
        file_path = "artifacts/bookings.csv"

        # Ask team name
        team_name = input("Enter team name: ")

        # Create booking record
        new_booking = {
            "ground_name": top["ground_name"],
            "date": date,
            "booked_by": team_name
        }

        new_df = pd.DataFrame([new_booking])

        # Check if file exists
        if os.path.exists(file_path):
            existing_df = pd.read_csv(file_path)

            # 🚫 Prevent duplicate booking
            if ((existing_df["ground_name"] == top["ground_name"]) & 
                (existing_df["date"] == date)).any():
                print("\n⚠️ This ground is already booked for this date!")
                return

            # Append
            new_df.to_csv(file_path, mode='a', header=False, index=False)
        else:
            new_df.to_csv(file_path, index=False)

        print("\n✅ Booking confirmed and saved!")

    elif choice == "no":
        print("\n❌ Booking cancelled.")

    else:
        print("\n⚠️ Invalid input. Please type 'yes' or 'no'.")

In [23]:
import pandas as pd

df = pd.read_csv("artifacts/bookings.csv")
print(df)

          ground_name        date   booked_by
0  NCC Cricket Ground  2026-03-25  colombo cc

In [24]:
def run_system():
    import pandas as pd
    import os

    # ===== INPUT =====
    city = input("Enter city: ").strip()
    date = input("Enter date (YYYY-MM-DD): ").strip()

    team_input = input("Enter team name (optional): ").strip()
    team_name = team_input if team_input != "" else None

    user_features = {
        "price_(lkr)": 120000,
        "rating": 4.5
    }

    # ===== RECOMMEND =====
    result = recommend_grounds(
        user_features=user_features,
        date=date,
        team_name=team_name,
        city=city,
        top_n=5
    )

    if result.empty:
        print("❌ No grounds found")
        return

    top = result.iloc[0]
    alt = result.iloc[1] if len(result) > 1 else None

    # ===== OUTPUT =====
    print("\n🏟️ Ground Recommendation Result\n")
    print(f"🏆 Best Match: {top['ground_name']}")
    print(f"⭐ ML Score: {top['ml_score']:.2f}")
    print(f"📊 Final Score: {top['final_score']:.2f}")
    print(f"🌦️ Weather: {top['weather']}")

    # ===== WEATHER CHECK =====
    if "rain" in str(top["weather"]).lower():
        print("\n⚠️ Not suitable due to bad weather")

        if alt is not None:
            print(f"👉 Alternative: {alt['ground_name']}")
    else:
        print("✅ Suitable for play")

    # ===== BOOKING =====
    choice = input("\nDo you want to book? (yes/no): ").strip().lower()

    if choice == "yes":
        os.makedirs("artifacts", exist_ok=True)
        file_path = "artifacts/bookings.csv"

        team_name = team_name if team_name else "Anonymous"

        new_booking = {
            "ground_name": top["ground_name"],
            "date": date,
            "booked_by": team_name
        }

        new_df = pd.DataFrame([new_booking])

        if os.path.exists(file_path):
            existing_df = pd.read_csv(file_path)

            if ((existing_df["ground_name"] == top["ground_name"]) &
                (existing_df["date"] == date)).any():
                print("⚠️ Already booked for this date")
                return

            new_df.to_csv(file_path, mode='a', header=False, index=False)
        else:
            new_df.to_csv(file_path, index=False)

        print("✅ Booking saved!")

    elif choice == "no":
        print("❌ Booking cancelled")

    else:
        print("⚠️ Invalid input")

In [25]:
run_system()

Enter city:  colombo
Enter date (YYYY-MM-DD):  2026-10-16
Enter team name (optional):  colombo cc

KeyError: 'city'