In [1]:
import pandas as pd
import joblib

In [2]:
import pandas as pd
import joblib

# Load dataset
df = pd.read_csv("../artifacts/Ground_clean_dataset.csv")

# Load trained ML components
rf_model = joblib.load("../artifacts/rf_model.joblib")
scaler = joblib.load("../artifacts/scaler.joblib")
model_features = joblib.load("../artifacts/model_features1.joblib")

print("Dataset and model loaded successfully")

Dataset and model loaded successfully

In [3]:
# Columns used in training
yes_no_cols = ["Lights", "Parking", "Washrooms", "Pavilion", "Scoreboard"]
numeric_cols = ["Length", "Width", "Rooms", "Parking Cap.", "Price (LKR)", "Rating"]
categorical_cols = ["City", "District", "Province", "Ground Type", "Pitch"]

# Pre-calc medians & modes
num_medians = {col: df[col].median() for col in numeric_cols}
cat_modes = {col: df[col].mode()[0] for col in categorical_cols}

print("Helper stats ready")

Helper stats ready

### normal Ground Search

In [4]:
def search_grounds(
    city=None,
    district=None,
    province=None,
    ground_type=None,
    pitch=None,
    needs_lights=None,
    needs_parking=None,
    max_price=None
):

    results = df.copy()

    # Normalize text inputs to lowercase 
    city_l        = city.lower().strip()        if city else None
    district_l    = district.lower().strip()    if district else None
    province_l    = province.lower().strip()    if province else None
    ground_type_l = ground_type.lower().strip() if ground_type else None
    pitch_l       = pitch.lower().strip()       if pitch else None

    if city_l:
        results = results[results["City"].str.lower() == city_l]

    if district_l:
        results = results[results["District"].str.lower() == district_l]

    if province_l:
        results = results[results["Province"].str.lower() == province_l]

    if ground_type_l:
        results = results[results["Ground Type"].str.lower() == ground_type_l]

    if pitch_l:
        results = results[results["Pitch"].str.lower() == pitch_l]

    if needs_lights is not None:
        results = results[results["Lights"] == ("Yes" if needs_lights else "No")]

    if needs_parking is not None:
        results = results[results["Parking"] == ("Yes" if needs_parking else "No")]

    if max_price is not None:
        results = results[results["Price (LKR)"] <= max_price]

    if results.empty:
        print("No grounds found for these filters.")
        return

    cols_to_show = [
        "Ground Name",
        "City",
        "District",
        "Province",
        "Ground Type",
        "Pitch",
        "Lights",
        "Parking",
        "Price (LKR)",
        "Rooms",
        "Rating"
    ]
    return results[cols_to_show]

In [5]:
search_grounds(city="colombo")

,Ground Name,City,District,Province,Ground Type,Pitch,Lights,Parking,Price (LKR),Rooms,Rating
59,Boralesgamuwa Public Ground,Colombo,Colombo,Western,Public,matting,No,Yes,13346.0,1.0,3.0
73,Colombo (Galle Face) Green,Colombo,Colombo,Western,Public,matting,No,Yes,13861.0,1.0,2.0
74,Colombo Ace Capital Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,153892.0,2.0,5.0
75,Colombo Air Force Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,184781.0,2.0,5.0
76,Colombo Ananda College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,81950.0,2.0,5.0
77,Colombo Barrack Square Grounds,Colombo,Colombo,Western,Public,matting,No,Yes,19979.0,1.0,3.0
78,Colombo Bloomfield Cricket & Athletic Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,146554.0,2.0,5.0
79,Colombo Burgher Recreation Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,170999.0,2.0,5.0
80,Colombo Colts Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,158279.0,2.0,5.0
81,Colombo Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,186742.0,2.0,5.0
82,Colombo DS Senanayake College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,134785.0,2.0,5.0
84,Colombo Galle Face Green,Colombo,Colombo,Western,Public,matting,No,Yes,14614.0,1.0,3.0
85,Colombo Health Ground,Colombo,Colombo,Western,Public,matting,No,Yes,10298.0,1.0,2.0
86,Colombo Malay Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,108073.0,2.0,5.0
87,Colombo Moors Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,111562.0,2.0,4.0
89,Colombo Nalanda College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,100085.0,2.0,5.0
90,Colombo Nondescripts Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,176459.0,2.0,5.0
91,Colombo P Sara Oval,Colombo,Colombo,Western,Public,turf,Yes,Yes,185582.0,2.0,5.0
92,Colombo Police Park Ground,Colombo,Colombo,Western,Public,turf,Yes,Yes,197470.0,2.0,5.0
93,Colombo Railway Ground,Colombo,Colombo,Western,Public,matting,No,Yes,18770.0,1.0,3.0
94,Colombo R Premadasa Stadium,Colombo,Colombo,Western,Public,turf,Yes,Yes,184888.0,2.0,5.0
95,Colombo Racquet Court,Colombo,Colombo,Western,Public,matting,No,Yes,19843.0,1.0,3.0
96,Colombo Sinhalese Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,183654.0,2.0,5.0
97,Colombo University Ground,Colombo,Colombo,Western,School,matting,No,Yes,28479.0,2.0,3.0
98,Colombo Vihara Mahadevi Park,Colombo,Colombo,Western,Public,matting,No,Yes,8453.0,1.0,3.0
99,Colombo Wesley College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,121194.0,2.0,5.0
136,Hanwella Public Ground,Colombo,Colombo,Western,Public,matting,No,Yes,17720.0,1.0,3.0
139,Havelock Park,Colombo,Colombo,Western,Public,matting,No,Yes,16292.0,1.0,3.0
400,Colombo City Cricket Park,Colombo,Colombo,Western,Club,turf,Yes,Yes,45000.0,3.0,5.0
401,Colombo Community Ground,Colombo,Colombo,Western,Public,matting,No,Yes,18000.0,1.0,3.0
402,Colombo Youth Oval,Colombo,Colombo,Western,Club,turf,Yes,Yes,32000.0,2.0,4.0
403,Colombo School Ground,Colombo,Colombo,Western,School,matting,No,Yes,20000.0,2.0,3.0
404,Colombo Riverside Field,Colombo,Colombo,Western,Public,turf,Yes,Yes,55000.0,3.0,5.0
490,Sinhalese Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,95000.0,4.0,5.0
491,Paikiasothy Saravanamuttu Stadium,Colombo,Colombo,Western,Club,turf,Yes,Yes,87000.0,3.0,5.0
492,Colombo Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,76000.0,3.0,5.0
493,Thurstan College Cricket Ground,Colombo,Colombo,Western,School,matting,No,Yes,22000.0,2.0,3.0
494,Royal College Sports Complex,Colombo,Colombo,Western,School,turf,Yes,Yes,38000.0,2.0,4.0
520,Ananda College Cricket Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,34000.0,2.0,4.0
521,Nalanda College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,33000.0,2.0,4.0
522,Isipathana College Ground,Colombo,Colombo,Western,School,matting,No,Yes,21000.0,2.0,3.0
523,Wesley College Cricket Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,35000.0,2.0,4.0
524,St. Joseph’s College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,36000.0,2.0,4.0
525,Bloomfield Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,42000.0,3.0,4.0
526,Colts Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,43000.0,3.0,4.0
527,Moors Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,41000.0,3.0,4.0
528,NCC Cricket Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,47000.0,3.0,5.0
529,Police Park Cricket Ground,Colombo,Colombo,Western,Public,turf,Yes,Yes,39000.0,2.0,4.0
530,Zahira College Cricket Ground,Colombo,Colombo,Western,School,matting,No,Yes,20000.0,2.0,3.0
531,Carey College Cricket Ground,Colombo,Colombo,Western,School,matting,No,Yes,20000.0,2.0,3.0
532,St. Benedict's College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,33000.0,2.0,4.0
534,University of Colombo Grounds,Colombo,Colombo,Western,Public,matting,No,Yes,17000.0,1.0,3.0
885,Police Park Ground,Colombo,Colombo,Western,Public,turf,Yes,Yes,55000.0,2.0,4.0

In [6]:
search_grounds(
    province="Western",
    pitch="turf",
    needs_lights=True,
    max_price=150000
)

,Ground Name,City,District,Province,Ground Type,Pitch,Lights,Parking,Price (LKR),Rooms,Rating
76,Colombo Ananda College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,81950.0,2.0,5.0
78,Colombo Bloomfield Cricket & Athletic Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,146554.0,2.0,5.0
82,Colombo DS Senanayake College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,134785.0,2.0,5.0
86,Colombo Malay Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,108073.0,2.0,5.0
87,Colombo Moors Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,111562.0,2.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...
905,Kalutara Municipal Sports Ground,Kalutara,Kalutara,Western,Public,turf,Yes,Yes,42000.0,2.0,4.0
906,Panadura Municipal Cricket Ground,Panadura,Kalutara,Western,Public,turf,Yes,Yes,41000.0,2.0,4.0
907,Gampaha Urban Council Ground,Gampaha,Gampaha,Western,Public,turf,Yes,Yes,39000.0,2.0,4.0
908,Negombo Urban Council Ground,Negombo,Gampaha,Western,Public,turf,Yes,Yes,38000.0,2.0,4.0
909,Moratuwa Urban Council Ground,Moratuwa,Colombo,Western,Public,turf,Yes,Yes,40000.0,2.0,4.0

In [7]:
search_grounds(city="colombo")

,Ground Name,City,District,Province,Ground Type,Pitch,Lights,Parking,Price (LKR),Rooms,Rating
59,Boralesgamuwa Public Ground,Colombo,Colombo,Western,Public,matting,No,Yes,13346.0,1.0,3.0
73,Colombo (Galle Face) Green,Colombo,Colombo,Western,Public,matting,No,Yes,13861.0,1.0,2.0
74,Colombo Ace Capital Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,153892.0,2.0,5.0
75,Colombo Air Force Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,184781.0,2.0,5.0
76,Colombo Ananda College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,81950.0,2.0,5.0
77,Colombo Barrack Square Grounds,Colombo,Colombo,Western,Public,matting,No,Yes,19979.0,1.0,3.0
78,Colombo Bloomfield Cricket & Athletic Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,146554.0,2.0,5.0
79,Colombo Burgher Recreation Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,170999.0,2.0,5.0
80,Colombo Colts Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,158279.0,2.0,5.0
81,Colombo Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,186742.0,2.0,5.0
82,Colombo DS Senanayake College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,134785.0,2.0,5.0
84,Colombo Galle Face Green,Colombo,Colombo,Western,Public,matting,No,Yes,14614.0,1.0,3.0
85,Colombo Health Ground,Colombo,Colombo,Western,Public,matting,No,Yes,10298.0,1.0,2.0
86,Colombo Malay Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,108073.0,2.0,5.0
87,Colombo Moors Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,111562.0,2.0,4.0
89,Colombo Nalanda College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,100085.0,2.0,5.0
90,Colombo Nondescripts Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,176459.0,2.0,5.0
91,Colombo P Sara Oval,Colombo,Colombo,Western,Public,turf,Yes,Yes,185582.0,2.0,5.0
92,Colombo Police Park Ground,Colombo,Colombo,Western,Public,turf,Yes,Yes,197470.0,2.0,5.0
93,Colombo Railway Ground,Colombo,Colombo,Western,Public,matting,No,Yes,18770.0,1.0,3.0
94,Colombo R Premadasa Stadium,Colombo,Colombo,Western,Public,turf,Yes,Yes,184888.0,2.0,5.0
95,Colombo Racquet Court,Colombo,Colombo,Western,Public,matting,No,Yes,19843.0,1.0,3.0
96,Colombo Sinhalese Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,183654.0,2.0,5.0
97,Colombo University Ground,Colombo,Colombo,Western,School,matting,No,Yes,28479.0,2.0,3.0
98,Colombo Vihara Mahadevi Park,Colombo,Colombo,Western,Public,matting,No,Yes,8453.0,1.0,3.0
99,Colombo Wesley College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,121194.0,2.0,5.0
136,Hanwella Public Ground,Colombo,Colombo,Western,Public,matting,No,Yes,17720.0,1.0,3.0
139,Havelock Park,Colombo,Colombo,Western,Public,matting,No,Yes,16292.0,1.0,3.0
400,Colombo City Cricket Park,Colombo,Colombo,Western,Club,turf,Yes,Yes,45000.0,3.0,5.0
401,Colombo Community Ground,Colombo,Colombo,Western,Public,matting,No,Yes,18000.0,1.0,3.0
402,Colombo Youth Oval,Colombo,Colombo,Western,Club,turf,Yes,Yes,32000.0,2.0,4.0
403,Colombo School Ground,Colombo,Colombo,Western,School,matting,No,Yes,20000.0,2.0,3.0
404,Colombo Riverside Field,Colombo,Colombo,Western,Public,turf,Yes,Yes,55000.0,3.0,5.0
490,Sinhalese Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,95000.0,4.0,5.0
491,Paikiasothy Saravanamuttu Stadium,Colombo,Colombo,Western,Club,turf,Yes,Yes,87000.0,3.0,5.0
492,Colombo Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,76000.0,3.0,5.0
493,Thurstan College Cricket Ground,Colombo,Colombo,Western,School,matting,No,Yes,22000.0,2.0,3.0
494,Royal College Sports Complex,Colombo,Colombo,Western,School,turf,Yes,Yes,38000.0,2.0,4.0
520,Ananda College Cricket Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,34000.0,2.0,4.0
521,Nalanda College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,33000.0,2.0,4.0
522,Isipathana College Ground,Colombo,Colombo,Western,School,matting,No,Yes,21000.0,2.0,3.0
523,Wesley College Cricket Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,35000.0,2.0,4.0
524,St. Joseph’s College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,36000.0,2.0,4.0
525,Bloomfield Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,42000.0,3.0,4.0
526,Colts Cricket Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,43000.0,3.0,4.0
527,Moors Sports Club Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,41000.0,3.0,4.0
528,NCC Cricket Ground,Colombo,Colombo,Western,Club,turf,Yes,Yes,47000.0,3.0,5.0
529,Police Park Cricket Ground,Colombo,Colombo,Western,Public,turf,Yes,Yes,39000.0,2.0,4.0
530,Zahira College Cricket Ground,Colombo,Colombo,Western,School,matting,No,Yes,20000.0,2.0,3.0
531,Carey College Cricket Ground,Colombo,Colombo,Western,School,matting,No,Yes,20000.0,2.0,3.0
532,St. Benedict's College Ground,Colombo,Colombo,Western,School,turf,Yes,Yes,33000.0,2.0,4.0
534,University of Colombo Grounds,Colombo,Colombo,Western,Public,matting,No,Yes,17000.0,1.0,3.0
885,Police Park Ground,Colombo,Colombo,Western,Public,turf,Yes,Yes,55000.0,2.0,4.0

In [8]:
search_grounds(city="Piliyandala")

,Ground Name,City,District,Province,Ground Type,Pitch,Lights,Parking,Price (LKR),Rooms,Rating
354,Piliyandala Central College Ground,Piliyandala,Colombo,Western,School,matting,No,Yes,35411.0,2.0,3.0
355,Piliyandala Public Ground,Piliyandala,Colombo,Western,Public,matting,No,Yes,8254.0,1.0,2.0
356,Piliyandala Sports Club Ground,Piliyandala,Colombo,Western,Club,matting,No,Yes,27516.0,2.0,4.0
810,Piliyandala Public Ground,Piliyandala,Colombo,Western,Public,matting,No,Yes,17000.0,1.0,3.0
811,Piliyandala Town Ground,Piliyandala,Colombo,Western,Public,turf,Yes,Yes,34000.0,2.0,4.0
812,Piliyandala Central College Ground,Piliyandala,Colombo,Western,School,matting,No,Yes,20000.0,2.0,3.0
813,Piliyandala Cricket Club Ground,Piliyandala,Colombo,Western,Club,turf,Yes,Yes,36000.0,2.0,4.0
814,Piliyandala Sports Complex,Piliyandala,Colombo,Western,Public,turf,Yes,Yes,42000.0,3.0,4.0

### ML-based Recommendation

In [9]:
def recommend_grounds(
    city=None,
    district=None,
    province=None,
    ground_type=None,
    pitch=None,
    needs_lights=None,
    needs_parking=None,
    max_price=None,
    top_n=5
):
    subset = df.copy()

    # Normalize text inputs
    city_l        = city.lower().strip()        if city else None
    district_l    = district.lower().strip()    if district else None
    province_l    = province.lower().strip()   if province else None
    ground_type_l = ground_type.lower().strip() if ground_type else None
    pitch_l       = pitch.lower().strip()       if pitch else None

    # Apply filters
    if city_l:
        subset = subset[subset["City"].str.lower() == city_l]

    if district_l:
        subset = subset[subset["District"].str.lower() == district_l]

    if province_l:
        subset = subset[subset["Province"].str.lower() == province_l]

    if ground_type_l:
        subset = subset[subset["Ground Type"].str.lower() == ground_type_l]

    if pitch_l:
        subset = subset[subset["Pitch"].str.lower() == pitch_l]

    if needs_lights is not None:
        subset = subset[subset["Lights"] == ("Yes" if needs_lights else "No")]

    if needs_parking is not None:
        subset = subset[subset["Parking"] == ("Yes" if needs_parking else "No")]

    if max_price is not None:
        subset = subset[subset["Price (LKR)"] <= max_price]

    if subset.empty:
        print("No grounds match these filters.")
        return

    # Preprocess for model
    temp = subset.copy()
    temp = temp.drop(columns=["Ground Name"])

    for col in yes_no_cols:
        temp[col] = temp[col].map({"Yes": 1, "No": 0})

    for col in numeric_cols:
        temp[col] = temp[col].fillna(num_medians[col])

    for col in categorical_cols:
        temp[col] = temp[col].fillna(cat_modes[col])

    temp_encoded = pd.get_dummies(temp, columns=categorical_cols, drop_first=True)
    temp_encoded = temp_encoded.reindex(columns=model_features, fill_value=0)

    temp_scaled = scaler.transform(temp_encoded)

    scores = rf_model.predict_proba(temp_scaled)[:, 1]

    subset["score"] = scores
    subset = subset.sort_values(by="score", ascending=False)

    return subset.head(top_n)

In [10]:
recommend_grounds(
    province="Western",
    pitch="matting",
    max_price=80000,
    top_n=5
)

,Unnamed: 0,Ground Name,City,District,Province,Ground Type,Pitch,Length,Width,Lights,Parking,Washrooms,Pavilion,Scoreboard,Rooms,Parking Cap.,Price (LKR),Rating,score
30,31.0,Athurugiriya Ground,Athurugiriya,Colombo,Western,Public,matting,108.0,112.0,No,Yes,Yes,No,Yes,1.0,17.0,3804.0,2.0,0.149216
431,431.0,Negombo Youth Ground,Negombo,Gampaha,Western,Public,matting,119.0,113.0,No,Yes,Yes,No,Yes,1.0,48.0,17000.0,3.0,0.149216
715,715.0,Kesbewa Public Ground,Kesbewa,Colombo,Western,Public,matting,118.0,112.0,No,Yes,Yes,No,No,1.0,50.0,17000.0,3.0,0.149216
717,717.0,Kesbewa Central College Ground,Kesbewa,Colombo,Western,School,matting,118.0,112.0,No,Yes,Yes,Yes,No,2.0,60.0,20000.0,3.0,0.149216
720,720.0,Horana Public Ground,Horana,Kalutara,Western,Public,matting,118.0,112.0,No,Yes,Yes,No,No,1.0,45.0,17000.0,3.0,0.149216

In [11]:
recommend_grounds(
    ground_type="Public",
    needs_lights=True,
    needs_parking=True,
    top_n=10
)

,Unnamed: 0,Ground Name,City,District,Province,Ground Type,Pitch,Length,Width,Lights,Parking,Washrooms,Pavilion,Scoreboard,Rooms,Parking Cap.,Price (LKR),Rating,score
0,1.0,Ambalangoda Esplanade,Ambalangoda,Galle,Southern,Public,turf,137.0,149.0,Yes,Yes,Yes,Yes,Yes,2.0,288.0,162417.0,5.0,0.149216
751,751.0,Peliyagoda Town Ground,Peliyagoda,Gampaha,Western,Public,turf,134.0,137.0,Yes,Yes,Yes,Yes,Yes,2.0,160.0,34000.0,4.0,0.149216
721,721.0,Horana Town Ground,Horana,Kalutara,Western,Public,turf,134.0,137.0,Yes,Yes,Yes,Yes,Yes,2.0,160.0,34000.0,4.0,0.149216
724,724.0,Horana Sports Complex,Horana,Kalutara,Western,Public,turf,138.0,141.0,Yes,Yes,Yes,Yes,Yes,3.0,200.0,42000.0,4.0,0.149216
726,726.0,Bandaragama Town Ground,Bandaragama,Kalutara,Western,Public,turf,134.0,137.0,Yes,Yes,Yes,Yes,Yes,2.0,160.0,34000.0,4.0,0.149216
729,729.0,Bandaragama Sports Complex,Bandaragama,Kalutara,Western,Public,turf,138.0,141.0,Yes,Yes,Yes,Yes,Yes,3.0,200.0,42000.0,4.0,0.149216
731,731.0,Kaduwela Town Ground,Kaduwela,Colombo,Western,Public,turf,134.0,137.0,Yes,Yes,Yes,Yes,Yes,2.0,160.0,34000.0,4.0,0.149216
734,734.0,Kaduwela Sports Complex,Kaduwela,Colombo,Western,Public,turf,138.0,141.0,Yes,Yes,Yes,Yes,Yes,3.0,200.0,40000.0,4.0,0.149216
736,736.0,Maharagama Town Ground,Maharagama,Colombo,Western,Public,turf,134.0,137.0,Yes,Yes,Yes,Yes,Yes,2.0,160.0,34000.0,4.0,0.149216
739,739.0,Maharagama Sports Complex,Maharagama,Colombo,Western,Public,turf,138.0,141.0,Yes,Yes,Yes,Yes,Yes,3.0,200.0,42000.0,4.0,0.149216