In [1]:
import numpy as numpy

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
import pandas as pd
print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

In [4]:
import os
os.getcwd()

'/Users/vimukthi/Documents/FYP/ML-based-Cricket-ground-recordation-project 2/notebooks'

In [5]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /opt/anaconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in /opt/anaconda3/lib/python3.13/site-packages (from openpyxl) (2.0.0)

In [6]:
import pandas as pd

pd.read_excel("../artifacts/Ground clean dataset.xlsx") \
    .to_csv("../artifacts/Ground_clean_dataset.csv", index=False)

In [7]:
import pandas as pd

df_raw = pd.read_csv("../artifacts/Ground_clean_dataset.csv")

df_raw.head()

,Unnamed: 0,Ground Name,City,District,Province,Ground Type,Pitch,Length,Width,Lights,Parking,Washrooms,Pavilion,Scoreboard,Rooms,Parking Cap.,Price (LKR),Rating
0,1.0,Ambalangoda Esplanade,Ambalangoda,Galle,Southern,Public,turf,137.0,149.0,Yes,Yes,Yes,Yes,Yes,2.0,288.0,162417.0,5.0
1,2.0,Ambalangoda High School Ground,Ambalangoda,Galle,Southern,School,matting,100.0,104.0,No,Yes,Yes,Yes,No,2.0,27.0,26760.0,3.0
2,3.0,Ambalangoda Oval,Ambalangoda,Galle,Southern,Public,turf,135.0,134.0,Yes,Yes,Yes,Yes,Yes,2.0,268.0,147946.0,4.0
3,4.0,Ambalangoda Playground,Ambalangoda,Galle,Southern,Public,matting,112.0,105.0,No,Yes,Yes,No,Yes,1.0,26.0,7371.0,2.0
4,5.0,Ambalangoda Public Ground,Ambalangoda,Galle,Southern,Public,matting,121.0,106.0,No,Yes,Yes,No,Yes,1.0,29.0,11911.0,3.0

In [8]:
df = pd.read_csv("../artifacts/Ground_clean_dataset.csv")

In [9]:
df.head()

,Unnamed: 0,Ground Name,City,District,Province,Ground Type,Pitch,Length,Width,Lights,Parking,Washrooms,Pavilion,Scoreboard,Rooms,Parking Cap.,Price (LKR),Rating
0,1.0,Ambalangoda Esplanade,Ambalangoda,Galle,Southern,Public,turf,137.0,149.0,Yes,Yes,Yes,Yes,Yes,2.0,288.0,162417.0,5.0
1,2.0,Ambalangoda High School Ground,Ambalangoda,Galle,Southern,School,matting,100.0,104.0,No,Yes,Yes,Yes,No,2.0,27.0,26760.0,3.0
2,3.0,Ambalangoda Oval,Ambalangoda,Galle,Southern,Public,turf,135.0,134.0,Yes,Yes,Yes,Yes,Yes,2.0,268.0,147946.0,4.0
3,4.0,Ambalangoda Playground,Ambalangoda,Galle,Southern,Public,matting,112.0,105.0,No,Yes,Yes,No,Yes,1.0,26.0,7371.0,2.0
4,5.0,Ambalangoda Public Ground,Ambalangoda,Galle,Southern,Public,matting,121.0,106.0,No,Yes,Yes,No,Yes,1.0,29.0,11911.0,3.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1038 entries, 0 to 1037
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    1037 non-null   float64
 1   Ground Name   1037 non-null   object
 2   City          1037 non-null   object
 3   District      1037 non-null   object
 4   Province      1037 non-null   object
 5   Ground Type   1037 non-null   object
 6   Pitch         1037 non-null   object
 7   Length        1037 non-null   float64
 8   Width         1037 non-null   float64
 9   Lights        1037 non-null   object
 10  Parking       1037 non-null   object
 11  Washrooms     1037 non-null   object
 12  Pavilion      1037 non-null   object
 13  Scoreboard    1037 non-null   object
 14  Rooms         1037 non-null   float64
 15  Parking Cap.  1037 non-null   float64
 16  Price (LKR)   1037 non-null   float64
 17  Rating        1037 non-null   float64
dtypes: float64(7), object(11)
memory usage: 146.1+ KB

In [11]:
# Drop useless index column
df = df.drop(columns=["Unnamed: 0"])

# Save identifiers separately
identifiers = df[["Ground Name"]]

# Drop identifiers from ML dataset
df_ml = df.drop(columns=["Ground Name"])

In [12]:
df_raw.columns = (
    df_raw.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace(".", "", regex=False)   # 🔥 ADD THIS LINE
)

In [13]:
print(df_raw.columns)

Index(['unnamed:_0', 'ground_name', 'city', 'district', 'province',
       'ground_type', 'pitch', 'length', 'width', 'lights', 'parking',
       'washrooms', 'pavilion', 'scoreboard', 'rooms', 'parking_cap',
       'price_lkr', 'rating'],
      dtype='object')

##Viva line:

“Identifier and index columns were removed as they do not contribute to predictive learning.”

### Convert YES / NO columns → 1 / 0

In [14]:
binary_cols = ["lights", "parking", "washrooms", "pavilion", "scoreboard"]

for col in binary_cols:
    df_raw[col] = df_raw[col].astype(str).str.upper().map({
        "YES": 1,
        "NO": 0
    })

In [15]:
yes_no_cols = [
    "Lights",
    "Parking",
    "Washrooms",
    "Pavilion",
    "Scoreboard"
]

In [16]:
df_ml = df.drop(columns=["Ground Name"])

In [17]:
for col in yes_no_cols:
    df_ml[col] = df_ml[col].map({"Yes": 1, "No": 0})

## Viva line:

“Binary facility attributes were converted into numerical format to make them machine-readable.”

### Handle missing values

In [18]:
numeric_cols = [
    "length",
    "width",
    "rooms",
    "parking_cap",
    "price_lkr",
    "rating"
]

In [19]:
numeric_cols = [
    "length",
    "width",
    "rooms",
    "parking_cap",
    "price_lkr",
    "rating"
]

In [20]:
categorical_cols = [
    "city",
    "district",
    "province",
    "ground_type",
    "pitch"
]

##Viva gold:

“Missing values were handled using median for numerical attributes and mode for categorical attributes.”

### Encode categorical columns

In [21]:
categorical_cols = [
    "city",
    "district",
    "province",
    "ground_type",
    "pitch"
]

In [22]:
df_raw.columns

Index(['unnamed:_0', 'ground_name', 'city', 'district', 'province',
       'ground_type', 'pitch', 'length', 'width', 'lights', 'parking',
       'washrooms', 'pavilion', 'scoreboard', 'rooms', 'parking_cap',
       'price_lkr', 'rating'],
      dtype='object')

In [23]:
df_raw["target"] = (df_raw["rating"] >= 4).astype(int)

In [24]:
df_ml = df_raw.drop(columns=["ground_name", "rating"])

In [25]:
df_encoded = pd.get_dummies(
    df_ml,
    columns=categorical_cols,
    drop_first=True
)

### Create TARGET variable

## Viva line:

“A binary target variable was created based on the ground rating to enable classification.”

In [26]:
X = df_encoded.drop(columns=["target"])
y = df_encoded["target"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (1038, 198)
Target shape: (1038,)

In [27]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Split & scaling done")
print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

Split & scaling done
X_train_scaled shape: (830, 198)
X_test_scaled shape: (208, 198)

### Decision Tree

In [28]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)

In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

#Create the Decision Tree model
dt_model = DecisionTreeClassifier(
    random_state=42,   
    max_depth=6        
)

#fit the model on training data
dt_model.fit(X_train_scaled, y_train)

# Predict on the test data
y_pred_dt = dt_model.predict(X_test_scaled)

# Evaluate the model
print("Decision Tree Performance")
print("----------------------------")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dt))

Decision Tree Performance
----------------------------
Accuracy: 0.9903846153846154

Classification Report:

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       122
           1       1.00      0.98      0.99        86

    accuracy                           0.99       208
   macro avg       0.99      0.99      0.99       208
weighted avg       0.99      0.99      0.99       208

In [30]:
print("X_train_scaled exists?", "X_train_scaled" in globals())
print("y_train exists?", "y_train" in globals())

X_train_scaled exists? True
y_train exists? True

### Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier

# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    max_depth=8,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight="balanced"
)

# Train the model
rf_model.fit(X_train_scaled, y_train)

# Predict on test data
y_pred_rf = rf_model.predict(X_test_scaled)

# Evaluate
print("Random Forest Performance")
print("----------------------------")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

# Check overfitting
print("\nTrain Accuracy:", rf_model.score(X_train_scaled, y_train))
print("Test Accuracy:", rf_model.score(X_test_scaled, y_test))

Random Forest Performance
----------------------------
Accuracy: 0.9903846153846154

Classification Report:

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       122
           1       1.00      0.98      0.99        86

    accuracy                           0.99       208
   macro avg       0.99      0.99      0.99       208
weighted avg       0.99      0.99      0.99       208


Train Accuracy: 0.9927710843373494
Test Accuracy: 0.9903846153846154

In [32]:
print("Train Accuracy:", rf_model.score(X_train_scaled, y_train))
print("Test Accuracy:", rf_model.score(X_test_scaled, y_test))

Train Accuracy: 0.9927710843373494
Test Accuracy: 0.9903846153846154

In [33]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(rf_model, X_train_scaled, y_train, cv=5)

print("CV Scores:", cv_scores)
print("Average:", cv_scores.mean())

CV Scores: [0.98795181 0.98192771 1.         0.97590361 0.9939759 ]
Average: 0.9879518072289157

In [34]:
cv_scores = cross_val_score(rf_model, X_train_scaled, y_train, cv=5)
print(cv_scores)
print(cv_scores.mean())

[0.98795181 0.98192771 1.         0.97590361 0.9939759 ]
0.9879518072289157

## Decision Tree vs Random Forest

| Model         | Accuracy  | Reason                                   |
| ------------- | --------- | ---------------------------------------- |
| Decision Tree | 92%       | Simple, interpretable baseline           |
| Random Forest | **97.3%** | Better generalization, ensemble learning |

Random Forest was selected as the final model due to its superior performance and robustness.

### Feature importance

In [35]:
# Feature importance from Random Forest
feature_importances = pd.DataFrame({
    "feature": X.columns,
    "importance": rf_model.feature_importances_
})

# Sort from most important to least
feature_importances = feature_importances.sort_values(
    by="importance",
    ascending=False
)

feature_importances.head(15)

                    feature  importance
197              pitch_turf    0.167992
3                    lights    0.132019
2                     width    0.117355
196           pitch_matting    0.108623
9               parking_cap    0.098597
1                    length    0.087361
8                     rooms    0.070528
6                  pavilion    0.060222
7                scoreboard    0.043209
10                price_lkr    0.040129
0                unnamed:_0    0.018646
195      ground_type_School    0.012440
179       district_Puttalam    0.009691
187  province_North Western    0.005012
143           city_Puttalam    0.004942

In [36]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(rf_model, X_train_scaled, y_train, cv=5)

print("Cross Validation Scores:", scores)
print("Average CV Score:", scores.mean())

Cross Validation Scores: [0.98795181 0.98192771 1.         0.97590361 0.9939759 ]
Average CV Score: 0.9879518072289157

In [37]:
import joblib

# Save trained model
joblib.dump(rf_model, "../artifacts/rf_model.joblib")
joblib.dump(scaler, "../artifacts/scaler.joblib")
joblib.dump(list(X.columns), "../artifacts/model_features1.joblib")

print("Model, scaler and feature list saved.")

Model, scaler and feature list saved.