In [1]:
import numpy as numpy

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
print("Pandas version:", pd.__version__)

Pandas version: 2.3.3

In [4]:
import os
os.getcwd()

'/Users/vimukthi/Documents/FYP/ML-based-Cricket-ground-recordation-project 2/notebooks'

In [5]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /opt/anaconda3/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et_xmlfile in /opt/anaconda3/lib/python3.13/site-packages (from openpyxl) (2.0.0)

In [6]:

pd.read_excel("../artifacts/Ground clean dataset.xlsx") \
    .to_csv("../artifacts/Ground_clean_dataset.csv", index=False)

In [7]:

df_raw = pd.read_csv("../artifacts/Ground_clean_dataset.csv")

df_raw.head()

,Unnamed: 0,Ground Name,City,District,Province,Ground Type,Pitch,Length,Width,Lights,Parking,Washrooms,Pavilion,Scoreboard,Rooms,Parking Cap.,Price (LKR),Rating
0,1.0,Ambalangoda Esplanade,Ambalangoda,Galle,Southern,Public,turf,137.0,149.0,Yes,Yes,Yes,Yes,Yes,2.0,288.0,162417.0,5.0
1,2.0,Ambalangoda High School Ground,Ambalangoda,Galle,Southern,School,matting,100.0,104.0,No,Yes,Yes,Yes,No,2.0,27.0,26760.0,3.0
2,3.0,Ambalangoda Oval,Ambalangoda,Galle,Southern,Public,turf,135.0,134.0,Yes,Yes,Yes,Yes,Yes,2.0,268.0,147946.0,4.0
3,4.0,Ambalangoda Playground,Ambalangoda,Galle,Southern,Public,matting,112.0,105.0,No,Yes,Yes,No,Yes,1.0,26.0,7371.0,2.0
4,5.0,Ambalangoda Public Ground,Ambalangoda,Galle,Southern,Public,matting,121.0,106.0,No,Yes,Yes,No,Yes,1.0,29.0,11911.0,3.0

In [8]:
df = pd.read_csv("../artifacts/Ground_clean_dataset.csv")

In [9]:
df.head()

,Unnamed: 0,Ground Name,City,District,Province,Ground Type,Pitch,Length,Width,Lights,Parking,Washrooms,Pavilion,Scoreboard,Rooms,Parking Cap.,Price (LKR),Rating
0,1.0,Ambalangoda Esplanade,Ambalangoda,Galle,Southern,Public,turf,137.0,149.0,Yes,Yes,Yes,Yes,Yes,2.0,288.0,162417.0,5.0
1,2.0,Ambalangoda High School Ground,Ambalangoda,Galle,Southern,School,matting,100.0,104.0,No,Yes,Yes,Yes,No,2.0,27.0,26760.0,3.0
2,3.0,Ambalangoda Oval,Ambalangoda,Galle,Southern,Public,turf,135.0,134.0,Yes,Yes,Yes,Yes,Yes,2.0,268.0,147946.0,4.0
3,4.0,Ambalangoda Playground,Ambalangoda,Galle,Southern,Public,matting,112.0,105.0,No,Yes,Yes,No,Yes,1.0,26.0,7371.0,2.0
4,5.0,Ambalangoda Public Ground,Ambalangoda,Galle,Southern,Public,matting,121.0,106.0,No,Yes,Yes,No,Yes,1.0,29.0,11911.0,3.0

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1038 entries, 0 to 1037
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Unnamed: 0    1037 non-null   float64
 1   Ground Name   1037 non-null   object
 2   City          1037 non-null   object
 3   District      1037 non-null   object
 4   Province      1037 non-null   object
 5   Ground Type   1037 non-null   object
 6   Pitch         1037 non-null   object
 7   Length        1037 non-null   float64
 8   Width         1037 non-null   float64
 9   Lights        1037 non-null   object
 10  Parking       1037 non-null   object
 11  Washrooms     1037 non-null   object
 12  Pavilion      1037 non-null   object
 13  Scoreboard    1037 non-null   object
 14  Rooms         1037 non-null   float64
 15  Parking Cap.  1037 non-null   float64
 16  Price (LKR)   1037 non-null   float64
 17  Rating        1037 non-null   float64
dtypes: float64(7), object(11)
memory usage: 146.1+ KB

In [11]:
# Drop useless index column
df = df.drop(columns=["Unnamed: 0"])

# Save identifiers separately
identifiers = df[["Ground Name"]]

# Drop identifiers from ML dataset
df_ml = df.drop(columns=["Ground Name"])

In [12]:
df_raw.columns = (
    df_raw.columns
    .str.lower()
    .str.strip()
    .str.replace(" ", "_")
    .str.replace("(", "", regex=False)
    .str.replace(")", "", regex=False)
    .str.replace(".", "", regex=False)   # 🔥 ADD THIS LINE
)

In [13]:
print(df_raw.columns)

Index(['unnamed:_0', 'ground_name', 'city', 'district', 'province',
       'ground_type', 'pitch', 'length', 'width', 'lights', 'parking',
       'washrooms', 'pavilion', 'scoreboard', 'rooms', 'parking_cap',
       'price_lkr', 'rating'],
      dtype='object')

##Viva line:

“Identifier and index columns were removed as they do not contribute to predictive learning.”

### Convert YES / NO columns → 1 / 0

In [14]:
binary_cols = ["lights", "parking", "washrooms", "pavilion", "scoreboard"]

for col in binary_cols:
    df_raw[col] = df_raw[col].astype(str).str.upper().map({
        "YES": 1,
        "NO": 0
    })

In [15]:
yes_no_cols = [
    "Lights",
    "Parking",
    "Washrooms",
    "Pavilion",
    "Scoreboard"
]

In [16]:
df_ml = df.drop(columns=["Ground Name"])

In [17]:
for col in yes_no_cols:
    df_ml[col] = df_ml[col].map({"Yes": 1, "No": 0})

## Viva line:

“Binary facility attributes were converted into numerical format to make them machine-readable.”

### Handle missing values

In [18]:
numeric_cols = [
    "length",
    "width",
    "rooms",
    "parking_cap",
    "price_lkr",
    "rating"
]

In [19]:
numeric_cols = [
    "length",
    "width",
    "rooms",
    "parking_cap",
    "price_lkr",
    "rating"
]

In [20]:
categorical_cols = [
    "city",
    "district",
    "province",
    "ground_type",
    "pitch"
]

##Viva gold:

“Missing values were handled using median for numerical attributes and mode for categorical attributes.”

### Encode categorical columns

In [21]:
categorical_cols = [
    "city",
    "district",
    "province",
    "ground_type",
    "pitch"
]

In [22]:
df_raw.columns

Index(['unnamed:_0', 'ground_name', 'city', 'district', 'province',
       'ground_type', 'pitch', 'length', 'width', 'lights', 'parking',
       'washrooms', 'pavilion', 'scoreboard', 'rooms', 'parking_cap',
       'price_lkr', 'rating'],
      dtype='object')

In [23]:
df_raw["target"] = (df_raw["rating"] >= 4).astype(int)

In [24]:
df_ml = df_raw.drop(columns=["ground_name", "rating"])

In [25]:
df_encoded = pd.get_dummies(
    df_ml,
    columns=categorical_cols,
    drop_first=True
)

### Create TARGET variable

## Viva line:

“A binary target variable was created based on the ground rating to enable classification.”

In [26]:
X = df_encoded.drop(columns=["target"])
y = df_encoded["target"]

print("Features shape:", X.shape)
print("Target shape:", y.shape)

Features shape: (1038, 198)
Target shape: (1038,)

In [27]:

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# Feature scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print("Split & scaling done")
print("X_train_scaled shape:", X_train_scaled.shape)
print("X_test_scaled shape:", X_test_scaled.shape)

Split & scaling done
X_train_scaled shape: (830, 198)
X_test_scaled shape: (208, 198)

### Decision Tree

In [28]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.13/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.22.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (2.3.5)
Requirement already satisfied: scipy>=1.8.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.13/site-packages (from scikit-learn) (3.5.0)

In [29]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

#Create the Decision Tree model
dt_model = DecisionTreeClassifier(
    random_state=42,   
    max_depth=6        
)

#fit the model on training data
dt_model.fit(X_train_scaled, y_train)

# Predict on the test data
y_pred_dt = dt_model.predict(X_test_scaled)

# Evaluate the model
print("Decision Tree Performance")
print("----------------------------")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_dt))

Decision Tree Performance
----------------------------
Accuracy: 0.9903846153846154

Classification Report:

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       122
           1       1.00      0.98      0.99        86

    accuracy                           0.99       208
   macro avg       0.99      0.99      0.99       208
weighted avg       0.99      0.99      0.99       208

In [30]:
print("X_train_scaled exists?", "X_train_scaled" in globals())
print("y_train exists?", "y_train" in globals())

X_train_scaled exists? True
y_train exists? True

### Random Forest

In [31]:
from sklearn.ensemble import RandomForestClassifier

# Create Random Forest model
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42,
    max_depth=8,
    min_samples_split=5,
    min_samples_leaf=2,
    class_weight="balanced"
)

# Train the model
rf_model.fit(X_train_scaled, y_train)

# Predict on test data
y_pred_rf = rf_model.predict(X_test_scaled)

# Evaluate
print("Random Forest Performance")
print("----------------------------")
print("Accuracy:", accuracy_score(y_test, y_pred_rf))
print("\nClassification Report:\n")
print(classification_report(y_test, y_pred_rf))

# Check overfitting
print("\nTrain Accuracy:", rf_model.score(X_train_scaled, y_train))
print("Test Accuracy:", rf_model.score(X_test_scaled, y_test))

Random Forest Performance
----------------------------
Accuracy: 0.9903846153846154

Classification Report:

              precision    recall  f1-score   support

           0       0.98      1.00      0.99       122
           1       1.00      0.98      0.99        86

    accuracy                           0.99       208
   macro avg       0.99      0.99      0.99       208
weighted avg       0.99      0.99      0.99       208


Train Accuracy: 0.9927710843373494
Test Accuracy: 0.9903846153846154

In [32]:
print("Train Accuracy:", rf_model.score(X_train_scaled, y_train))
print("Test Accuracy:", rf_model.score(X_test_scaled, y_test))

Train Accuracy: 0.9927710843373494
Test Accuracy: 0.9903846153846154

In [33]:
from sklearn.model_selection import cross_val_score

cv_scores = cross_val_score(rf_model, X_train_scaled, y_train, cv=5)

print("CV Scores:", cv_scores)
print("Average:", cv_scores.mean())

CV Scores: [0.98795181 0.98192771 1.         0.97590361 0.9939759 ]
Average: 0.9879518072289157

In [34]:
cv_scores = cross_val_score(rf_model, X_train_scaled, y_train, cv=5)
print(cv_scores)
print(cv_scores.mean())

[0.98795181 0.98192771 1.         0.97590361 0.9939759 ]
0.9879518072289157

## Decision Tree vs Random Forest

| Model         | Accuracy  | Reason                                   |
| ------------- | --------- | ---------------------------------------- |
| Decision Tree | 92%       | Simple, interpretable baseline           |
| Random Forest | **97.3%** | Better generalization, ensemble learning |

Random Forest was selected as the final model due to its superior performance and robustness.

### Feature importance

In [35]:
# Feature importance from Random Forest
feature_importances = pd.DataFrame({
    "feature": X.columns,
    "importance": rf_model.feature_importances_
})

# Sort from most important to least
feature_importances = feature_importances.sort_values(
    by="importance",
    ascending=False
)

feature_importances.head(15)

                    feature  importance
197              pitch_turf    0.167992
3                    lights    0.132019
2                     width    0.117355
196           pitch_matting    0.108623
9               parking_cap    0.098597
1                    length    0.087361
8                     rooms    0.070528
6                  pavilion    0.060222
7                scoreboard    0.043209
10                price_lkr    0.040129
0                unnamed:_0    0.018646
195      ground_type_School    0.012440
179       district_Puttalam    0.009691
187  province_North Western    0.005012
143           city_Puttalam    0.004942

In [36]:

scores = cross_val_score(rf_model, X_train_scaled, y_train, cv=5)

print("Cross Validation Scores:", scores)
print("Average CV Score:", scores.mean())

Cross Validation Scores: [0.98795181 0.98192771 1.         0.97590361 0.9939759 ]
Average CV Score: 0.9879518072289157

In [37]:
import joblib

# Save trained model
joblib.dump(rf_model, "../artifacts/rf_model.joblib")
joblib.dump(scaler, "../artifacts/scaler.joblib")
joblib.dump(list(X.columns), "../artifacts/model_features1.joblib")

print("Model, scaler and feature list saved.")

Model, scaler and feature list saved.

In [38]:

pd.set_option('future.no_silent_downcasting', True)

In [39]:
import requests

API_KEY = "0943842962317c345fa1bc34ac6486ea"   # PI key

def get_weather(city, date):
    try:
        url = f"https://api.openweathermap.org/data/2.5/forecast?q={city}&appid={API_KEY}&units=metric"
        response = requests.get(url)
        data = response.json()


        if "list" not in data:
            return "Unknown"

        for item in data["list"]:
            if date in item["dt_txt"]:
                return item["weather"][0]["main"]

        return "Clear"   

    except:
        return "Unknown"

In [40]:
df = pd.read_csv("../artifacts/Ground_clean_dataset.csv")
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [41]:
bookings = pd.read_csv("../artifacts/bookings.csv")

In [42]:
model = joblib.load("../artifacts/rf_model.joblib")
scaler = joblib.load("../artifacts/scaler.joblib")
model_features = joblib.load("../artifacts/model_features1.joblib")

In [43]:

team_stats = pd.read_csv("../artifacts/team_stats.csv")

team_stats

,team_name,ground_name,matches_played_,wins,matches_played
0,Royal College XI,SSC Cricket Ground,NaN,7,10.0
1,Royal College XI,NCC Cricket Ground,NaN,5,8.0
2,Royal College XI,Colombo Colts Ground,NaN,4,7.0
3,Royal College XI,Colombo City Cricket Park,NaN,3,6.0
4,Royal College XI,P Sara Oval Ground,NaN,3,6.0
...,...,...,...,...,...
1309,Panadura SC,De Soysa Stadium,NaN,3,7.0
1310,Panadura SC,SSC Cricket Ground,NaN,2,6.0
1311,Panadura SC,NCC Cricket Ground,NaN,1,5.0
1312,Panadura SC,Colombo Colts Ground,NaN,2,5.0
1313,Panadura SC,P Sara Oval Ground,NaN,2,6.0

In [44]:
new_data = pd.DataFrame([
# Royal College XI
["Royal College XI","SSC Cricket Ground",10,7],
["Royal College XI","NCC Cricket Ground",8,5],
["Royal College XI","Colombo Colts Ground",7,4],
["Royal College XI","Colombo City Cricket Park",6,3],
["Royal College XI","P Sara Oval Ground",6,3],
["Royal College XI","Bloomfield Cricket Ground",5,2],
["Royal College XI","De Soysa Stadium",5,2],
["Royal College XI","Panadura Public Ground",4,1],

# St Joseph's
["St. Joseph's College XI","SSC Cricket Ground",10,7],
["St. Joseph's College XI","NCC Cricket Ground",8,4],
["St. Joseph's College XI","Colombo City Cricket Park",7,3],
["St. Joseph's College XI","Colombo Colts Ground",6,2],
["St. Joseph's College XI","P Sara Oval Ground",7,3],
["St. Joseph's College XI","Bloomfield Cricket Ground",6,2],
["St. Joseph's College XI","De Soysa Stadium",6,2],

# Ananda College XI
["Ananda College XI","SSC Cricket Ground",9,5],
["Ananda College XI","NCC Cricket Ground",7,3],
["Ananda College XI","Colombo Colts Ground",8,4],
["Ananda College XI","Colombo City Cricket Park",7,3],
["Ananda College XI","P Sara Oval Ground",7,3],
["Ananda College XI","Bloomfield Cricket Ground",6,2],
["Ananda College XI","De Soysa Stadium",5,2],
["Ananda College XI","Panadura Public Ground",4,1],

# Nalanda College XI
["Nalanda College XI","SSC Cricket Ground",8,4],
["Nalanda College XI","NCC Cricket Ground",7,3],
["Nalanda College XI","Colombo Colts Ground",9,5],
["Nalanda College XI","Colombo City Cricket Park",6,2],
["Nalanda College XI","P Sara Oval Ground",7,3],
["Nalanda College XI","Bloomfield Cricket Ground",6,2],
["Nalanda College XI","De Soysa Stadium",5,2],

# St Peter's
["St. Peter's College XI","SSC Cricket Ground",7,3],
["St. Peter's College XI","NCC Cricket Ground",6,2],
["St. Peter's College XI","Colombo Colts Ground",8,4],
["St. Peter's College XI","Colombo City Cricket Park",7,3],
["St. Peter's College XI","Bloomfield Cricket Ground",6,2],
["St. Peter's College XI","P Sara Oval Ground",6,2],

# Colombo CC
["Colombo CC","SSC Cricket Ground",12,9],
["Colombo CC","NCC Cricket Ground",10,7],
["Colombo CC","Colombo Colts Ground",9,6],
["Colombo CC","P Sara Oval Ground",8,5],
["Colombo CC","Bloomfield Cricket Ground",7,4],
["Colombo CC","De Soysa Stadium",8,5],
["Colombo CC","Panadura Public Ground",7,3],
["Colombo CC","Kalutara Public Ground",6,2],

# Sinhalese SC
["Sinhalese SC","SSC Cricket Ground",15,12],
["Sinhalese SC","NCC Cricket Ground",12,8],
["Sinhalese SC","Colombo Colts Ground",10,7],
["Sinhalese SC","P Sara Oval Ground",9,6],
["Sinhalese SC","Bloomfield Cricket Ground",8,5],
["Sinhalese SC","De Soysa Stadium",9,6],
["Sinhalese SC","Panadura Public Ground",8,4],
["Sinhalese SC","Kalutara Public Ground",7,3],

# NCC Club
["NCC Club","NCC Cricket Ground",14,10],
["NCC Club","SSC Cricket Ground",10,6],
["NCC Club","Colombo Colts Ground",9,5],
["NCC Club","P Sara Oval Ground",9,5],
["NCC Club","Bloomfield Cricket Ground",8,4],
["NCC Club","De Soysa Stadium",7,3],
["NCC Club","Panadura Public Ground",6,2],

# Moratuwa SC
["Moratuwa SC","De Soysa Stadium",10,7],
["Moratuwa SC","Moratuwa University Ground",6,3],
["Moratuwa SC","Kalutara Public Ground",8,4],
["Moratuwa SC","Panadura Public Ground",7,3],
["Moratuwa SC","SSC Cricket Ground",6,3],
["Moratuwa SC","NCC Cricket Ground",5,2],
["Moratuwa SC","Colombo Colts Ground",5,2],

# Panadura SC
["Panadura SC","Panadura Public Ground",10,6],
["Panadura SC","Kalutara Public Ground",8,3],
["Panadura SC","De Soysa Stadium",7,3],
["Panadura SC","SSC Cricket Ground",6,2],
["Panadura SC","NCC Cricket Ground",5,1],
["Panadura SC","Colombo Colts Ground",5,2],
["Panadura SC","P Sara Oval Ground",6,2]

], columns=["team_name","ground_name","matches_played","wins"])

In [45]:
team_stats

,team_name,ground_name,matches_played_,wins,matches_played
0,Royal College XI,SSC Cricket Ground,NaN,7,10.0
1,Royal College XI,NCC Cricket Ground,NaN,5,8.0
2,Royal College XI,Colombo Colts Ground,NaN,4,7.0
3,Royal College XI,Colombo City Cricket Park,NaN,3,6.0
4,Royal College XI,P Sara Oval Ground,NaN,3,6.0
...,...,...,...,...,...
1309,Panadura SC,De Soysa Stadium,NaN,3,7.0
1310,Panadura SC,SSC Cricket Ground,NaN,2,6.0
1311,Panadura SC,NCC Cricket Ground,NaN,1,5.0
1312,Panadura SC,Colombo Colts Ground,NaN,2,5.0
1313,Panadura SC,P Sara Oval Ground,NaN,2,6.0

In [46]:
file_path = "../artifacts/team_stats.csv"
team_stats = pd.concat([team_stats, new_data], ignore_index=True)
team_stats.to_csv(file_path, index=False)

In [47]:
def recommend_grounds(user_features, date, team_name=None, city=None, top_n=5):

    data = df.copy()

    # make all columns lowercase 
    data.columns = data.columns.str.lower().str.replace(" ", "_")

    #  FILTER BY CITY 
    if city and "city" in data.columns:
        data = data[data["city"].str.lower() == city.lower()]

    #  TEAM PERFORMANCE 
    if team_name:
        team_data = team_stats[team_stats["team_name"] == team_name].copy()

        if not team_data.empty:
            team_data["win_rate"] = team_data["wins"] / team_data["matches_played"]

            data = data.merge(team_data, on="ground_name", how="left")

            data["win_rate"] = data["win_rate"].fillna(0).astype(float)
            data["matches_played"] = data["matches_played"].fillna(0).astype(float)

            data = data.drop_duplicates(subset=["ground_name"])
        else:
            data["win_rate"] = 0
    else:
        data["win_rate"] = 0

    # WEATHER 
    if "city" in data.columns:
        data["weather"] = data["city"].apply(lambda x: get_weather(x, date))
    else:
        data["weather"] = "unknown"

    # WEATHER SCORE 
    def weather_score(condition):
        condition = str(condition).lower()
        if "rain" in condition or "storm" in condition:
            return 0
        elif "cloud" in condition:
            return 0.7
        else:
            return 1

    data["weather_score"] = data["weather"].apply(weather_score)

    # REMOVE BOOKED GROUNDS 
    if 'bookings' in globals() and not bookings.empty:
        booked = bookings[bookings["date"] == date]["ground_name"]
        data = data[~data["ground_name"].isin(booked)]

    # ML SCORING 
    categorical_cols = ["city", "district", "province", "ground_type", "pitch"]

    # One-hot encoding
    data_encoded = pd.get_dummies(data, columns=categorical_cols)

    # Align with trained model features
    data_encoded = data_encoded.reindex(columns=model_features, fill_value=0)

    # Convert to numeric
    data_encoded = data_encoded.apply(pd.to_numeric, errors='coerce').fillna(0)

    # Scale
    X_scaled = scaler.transform(data_encoded)

    # Predict
    scores = model.predict_proba(X_scaled)[:, 1]

    # Assign ML score
    data["ml_score"] = scores

    # FINAL HYBRID SCORE
    data["final_score"] = (
        data["ml_score"] * 0.4 +
        data["win_rate"] * 0.4 +
        data["weather_score"] * 0.2
    )

    # RETURN TOP RESULTS 
    return data.sort_values(by="final_score", ascending=False).head(top_n)

In [48]:
# Step 1: define input
user_input = {
    "price_(lkr)": 120000,
    "lights": 1,
    "parking": 1,
    "rating": 4
}

# Step 2: call function
result = recommend_grounds(
    user_input,
    date="2026-04-10",
    team_name="Royal College XI",
    city="colombo"
)

# step 3: output
top = result.iloc[0]
alt = result.iloc[1]

print("Ground Recommendation Result\n")

print("Best Match:")
print(f"{top['ground_name']} | Weather: {top['weather']}")

if "rain" in str(top["weather"]).lower():
    print("\n Not suitable due to bad weather")

    print("\n Alternative:")
    print(f"{alt['ground_name']} | Weather: {alt['weather']}")
else:
    print("\n Suitable for play")

Ground Recommendation Result

Best Match:
Colombo City Cricket Park | Weather: Clear

 Suitable for play

In [49]:
top = result.iloc[0]
alt = result.iloc[1] if len(result) > 1 else None

print("Ground Recommendation Result\n")

# Best Match
print(" Best for Match:")
print(f"Ground: {top['ground_name']}")
print(f"ML Score: {top['ml_score']:.2f}")
print(f"Win Rate: {top['win_rate']:.2f}")
print(f"Final Score: {top['final_score']:.2f}")
print(f"Weather: {top['weather']}")

# Weather check
if "rain" in str(top["weather"]).lower() or "storm" in str(top["weather"]).lower():

    print("\n Warning:")
    print("This ground is not suitable due to bad weather.")

    if alt is not None:
        print("\n Recommended Alternative:")
        print(f"Ground: {alt['ground_name']}")
        print(f"ML Score: {alt['ml_score']:.2f}")
        print(f"Win Rate: {alt['win_rate']:.2f}")
        print(f"Final Score: {alt['final_score']:.2f}")
        print(f"Weather: {alt['weather']}")

        print("\n Reason:")
        print("Better weather conditions for playing.")

else:
    print("\n This ground is suitable for play.")

Ground Recommendation Result

 Best for Match:
Ground: Colombo City Cricket Park
ML Score: 0.57
Win Rate: 0.50
Final Score: 0.63
Weather: Clear

 This ground is suitable for play.

In [50]:
top = result.iloc[0]
alt = result.iloc[1]

print(" Ground Recommendation Result\n")

print(" Best Match:")
print(f"{top['ground_name']} | Weather: {top['weather']}")

if "rain" in str(top["weather"]).lower():
    print("\n Not suitable due to bad weather")

    print("\n Alternative:")
    print(f"{alt['ground_name']} | Weather: {alt['weather']}")
else:
    print("\n Suitable for play")

 Ground Recommendation Result

 Best Match:
Colombo City Cricket Park | Weather: Clear

 Suitable for play

In [51]:
def run_system():
    city = input("Enter city: ").strip()
    date = input("Enter date (YYYY-MM-DD): ").strip()

    team_input = input("Enter team name (optional): ").strip()
    team_name = team_input if team_input != "" else None

    user_features = {
        "price_(lkr)": 120000,
        "rating": 4.5
    }

    # ---------------- RECOMMEND ----------------
    result = recommend_grounds(
        user_features=user_features,
        date=date,
        team_name=team_name,
        city=city,
        top_n=5
    )

    if result.empty:
        print("❌ No grounds found")
        return

    # ---------------- APPLY TEAM-BASED SCORING ----------------
    if team_name is not None:
        result["team_boost"] = result["win_rate"] * 0.2
    else:
        result["team_boost"] = 0

    # 🔥 Updated Final Score (IMPORTANT)
    result["final_score"] = (
        (result["ml_score"] * 0.5) +
        (result["win_rate"] * 0.3) +
        (result["team_boost"] * 0.2)
    )

    # Sort again after applying team influence
    result = result.sort_values(by="final_score", ascending=False).reset_index(drop=True)

    # ---------------- EXPLAIN AI FUNCTION ----------------
    def generate_explanation(row):
        reasons = []

        if row["final_score"] > 0.75:
            reasons.append("high overall score")

        if row["ml_score"] > 0.75:
            reasons.append("strong ML prediction")

        if row["win_rate"] > 0.70:
            reasons.append("good historical win rate")

        if team_name:
            reasons.append("team performance considered")

        if "clear" in str(row["weather"]).lower():
            reasons.append("clear weather conditions")

        if "cloud" in str(row["weather"]).lower():
            reasons.append("acceptable weather conditions")

        if "rain" in str(row["weather"]).lower():
            reasons.append("weather is risky")

        return ", ".join(reasons)

    # ---------------- BEST MATCH ----------------
    top = result.iloc[0]

    print("\n🎯 Ground Recommendation Result\n")

    print("⭐ Best Match:")
    print(f"Ground: {top['ground_name']}")
    print(f"ML Score: {top['ml_score']:.2f}")
    print(f"Win Rate: {top['win_rate']:.2f}")
    print(f"Final Score: {top['final_score']:.2f}")
    print(f"Weather: {top['weather']}")
    print(f"Explanation: {generate_explanation(top)}")

    # ---------------- WEATHER CHECK ----------------
    bad_weather = ["rain", "heavy rain", "storm"]
    alternatives = result.iloc[1:4]

    if any(w in str(top["weather"]).lower() for w in bad_weather):

        print("\n⚠️ Warning:")
        print("This ground is not suitable due to bad weather.\n")

        if not alternatives.empty:
            print("👉 Top 3 Best Alternative Grounds:")
            print("These are the next best options based on score and weather:\n")

            for i, (_, alt) in enumerate(alternatives.iterrows(), 1):
                print(f"\nAlternative {i}:")
                print(f"Ground: {alt['ground_name']}")
                print(f"ML Score: {alt['ml_score']:.2f}")
                print(f"Win Rate: {alt['win_rate']:.2f}")
                print(f"Final Score: {alt['final_score']:.2f}")
                print(f"Weather: {alt['weather']}")
                print(f"Explanation: {generate_explanation(alt)}")

        print("\n✅ Reason:")
        print("Better weather conditions and suitable for playing.")

    else:
        print("\n✅ This ground is suitable for play.")

    # ---------------- BOOKING ----------------
    print("\n🎯 these are the other best suitable grounds,Select a ground to book from the best options:")
    print(f"0 - {top['ground_name']}")

    for i, (_, alt) in enumerate(alternatives.iterrows(), 1):
        print(f"{i} - {alt['ground_name']}")

    choice = input("\nEnter option (0/1/2/3) or 'no': ").strip().lower()

    if choice in ["0", "1", "2", "3"]:


        os.makedirs("artifacts", exist_ok=True)
        file_path = "artifacts/bookings.csv"

        team_name_final = team_name if team_name else "Anonymous"

        # Select ground
        if choice == "0":
            selected = top
        else:
            index = int(choice) - 1
            if index < len(alternatives):
                selected = alternatives.iloc[index]
            else:
                print("❌ Invalid selection")
                return

        # Save booking
        new_df = pd.DataFrame([{
            "ground_name": selected["ground_name"],
            "date": date,
            "booked_by": team_name_final
        }])

        if os.path.exists(file_path):
            new_df.to_csv(file_path, mode='a', header=False, index=False)
        else:
            new_df.to_csv(file_path, index=False)

        print(f"✅ Booking saved for: {selected['ground_name']}")

    elif choice == "no":
        print("❌ Booking cancelled")

    else:
        print("⚠️ Invalid input")

In [52]:
run_system()

Enter city:  piliyandala
Enter date (YYYY-MM-DD):  2026-5-7
Enter team name (optional):  colombo cc

🎯 Ground Recommendation Result

⭐ Best Match:
Ground: Piliyandala Town Ground
ML Score: 0.59
Win Rate: 0.00
Final Score: 0.29
Weather: Clear
Explanation: team performance considered, clear weather conditions

✅ This ground is suitable for play.

🎯 these are the other best suitable grounds,Select a ground to book from the best options:
0 - Piliyandala Town Ground
1 - Piliyandala Sports Complex
2 - Piliyandala Cricket Club Ground
3 - Piliyandala Sports Club Ground

Enter option (0/1/2/3) or 'no':  3

✅ Booking saved for: Piliyandala Sports Club Ground

In [53]:

# 🔥 YOUR ACTUAL PATH
FILE_PATH = "artifacts/bookings.csv"

# Ensure file exists
if not os.path.exists(FILE_PATH):
    os.makedirs("artifacts", exist_ok=True)
    df = pd.DataFrame(columns=["ground_name", "date", "booked_by"])
    df.to_csv(FILE_PATH, index=False)

In [54]:
def view_all_bookings():
    df = pd.read_csv(FILE_PATH)

    if df.empty:
        print("📅 No bookings yet")
        return

    print("\n📅 All Bookings:\n")
    print(df.sort_values(by="date"))

In [55]:
def check_availability(ground_name, date):
    df = pd.read_csv(FILE_PATH)

    clash = df[
        (df["ground_name"] == ground_name) &
        (df["date"] == date)
    ]

    return clash.empty

In [56]:
def show_availability_for_date(date):
    df_bookings = pd.read_csv(FILE_PATH)

    # 🔥 Load all grounds from your dataset
    grounds_df = pd.read_csv("artifacts/Ground_clean_dataset.csv")

    print(f"\n📅 Availability for {date}:\n")

    for ground in grounds_df["ground_name"].unique():
        available = df_bookings[
            (df_bookings["ground_name"] == ground) &
            (df_bookings["date"] == date)
        ].empty

        status = "🟢 Available" if available else "🔴 Booked"
        print(f"{ground}: {status}")

In [57]:
def calendar_view_by_month(year, month):
    df = pd.read_csv(FILE_PATH)

    if df.empty:
        print("📅 No bookings yet")
        return

    # Convert date column to datetime
    df["date"] = pd.to_datetime(df["date"], errors='coerce')

    # Filter by year and month
    df_filtered = df[
        (df["date"].dt.year == year) &
        (df["date"].dt.month == month)
    ]

    if df_filtered.empty:
        print(f"📅 No bookings for {year}-{month:02d}")
        return

    print(f"\n📅 Calendar View for {year}-{month:02d}:\n")

    grouped = df_filtered.groupby(df_filtered["date"].dt.date)

    for date, group in grouped:
        print(f"\n📆 {date}")
        for _, row in group.iterrows():
            print(f"   🏟️ {row['ground_name']} (Booked by {row['booked_by']})")

In [58]:
calendar_view_by_month(2026, 10)

📅 Calendar View for 2026-10:


📆 2026-10-10
   🏟️ Police Park Ground (Booked by colombo cc)

📆 2026-10-20
   🏟️ Matara City Sports Ground (Booked by Sinhalese SC)

📆 2026-10-21
   🏟️ Piliyandala Sports Complex (Booked by colombo cc)

📆 2026-10-30
   🏟️ Police Park Ground (Booked by colombo cc)
   🏟️ Police Park Ground (Booked by colombo cc)

In [ ]:
## import uuid
from datetime import datetime


# ---------------- PLAYER ----------------
class Player:
    def __init__(self, name):
        self.name = name
        self.runs = 0
        self.balls = 0
        self.wickets = 0
        self.runs_conceded = 0


# ---------------- TEAM ----------------
class Team:
    def __init__(self, name):
        self.name = name
        self.players = []
        self.score = 0
        self.wickets = 0


# ---------------- SAVE FUNCTIONS ----------------
def save_all(match):
    os.makedirs("artifacts", exist_ok=True)

    # Ball log
    pd.DataFrame(match.ball_log).to_csv(
        "artifacts/match_log.csv", mode='a', index=False, header=False
    )

    # Batting
    bat = []
    for t in [match.teamA, match.teamB]:
        for p in t.players:
            if p.balls > 0:
                bat.append({
                    "match_id": match.match_id,
                    "team": t.name,
                    "player": p.name,
                    "runs": p.runs,
                    "balls": p.balls
                })
    pd.DataFrame(bat).to_csv("artifacts/batting_scorecard.csv", mode='a', index=False, header=False)

    # Bowling
    bowl = []
    for t in [match.teamA, match.teamB]:
        for p in t.players:
            if p.runs_conceded > 0 or p.wickets > 0:
                bowl.append({
                    "match_id": match.match_id,
                    "team": t.name,
                    "player": p.name,
                    "runs_conceded": p.runs_conceded,
                    "wickets": p.wickets
                })
    pd.DataFrame(bowl).to_csv("artifacts/bowling_scorecard.csv", mode='a', index=False, header=False)

    # Summary CSV
    pd.DataFrame([{
        "match_id": match.match_id,
        "date": datetime.now(),
        "teamA": match.teamA.name,
        "teamA_score": f"{match.teamA.score}/{match.teamA.wickets}",
        "teamB": match.teamB.name,
        "teamB_score": f"{match.teamB.score}/{match.teamB.wickets}",
        "winner": match.winner
    }]).to_csv("artifacts/match_summary.csv", mode='a', index=False, header=False)

    print("✅ ALL DATA SAVED")


# ---------------- MATCH SUMMARY DISPLAY ----------------
def show_match_summary(match):

    print("\n" + "="*40)
    print("🏏 MATCH SUMMARY")
    print("="*40)

    print(f"\n{match.teamA.name}: {match.teamA.score}/{match.teamA.wickets}")
    print(f"{match.teamB.name}: {match.teamB.score}/{match.teamB.wickets}")

    print(f"\n🏆 Winner: {match.winner}")

    all_players = match.teamA.players + match.teamB.players

    # Top batsman
    top_batsman = max(all_players, key=lambda x: x.runs)
    print(f"\n🔥 Top Batsman: {top_batsman.name} ({top_batsman.runs} runs)")

    # Top bowler
    top_bowler = max(all_players, key=lambda x: x.wickets)
    print(f"🎯 Top Bowler: {top_bowler.name} ({top_bowler.wickets} wickets)")

    print("="*40)


# ---------------- MATCH ----------------
class Match:
    def __init__(self, teamA, teamB, overs):
        self.teamA = teamA
        self.teamB = teamB
        self.overs = overs
        self.ball_log = []
        self.match_id = str(uuid.uuid4())[:8]

    def get_input(self):
        valid = ["0","1","2","3","4","6","W","WD","NB"]
        while True:
            b = input("Ball (0,1,2,3,4,6,W,WD,NB): ").upper()
            if b in valid:
                return b
            print("❌ Invalid!")

    def play(self, batting, bowling, innings):

        print(f"\n🏏 Innings {innings}: {batting.name}")

        striker = Player(input("Enter Striker name: "))
        non_striker = Player(input("Enter Non-Striker name: "))
        batting.players.extend([striker, non_striker])

        balls = 0
        bowler = None

        while balls < self.overs * 6 and batting.wickets < 10:

            if balls % 6 == 0:
                bowler = Player(input("\nEnter Bowler name: "))
                bowling.players.append(bowler)

            over = balls//6 + 1
            ball_no = balls%6 + 1

            print(f"\nOver {over}.{ball_no}")
            print(f"{batting.score}/{batting.wickets}")

            ball = self.get_input()

            # LOG
            self.ball_log.append({
                "match_id": self.match_id,
                "innings": innings,
                "over": over,
                "ball": ball_no,
                "batsman": striker.name,
                "bowler": bowler.name,
                "event": ball
            })

            if ball == "W":
                batting.wickets += 1
                bowler.wickets += 1
                print(f"{striker.name} OUT!")

                striker = Player(input("Enter next batsman: "))
                batting.players.append(striker)

            elif ball in ["WD","NB"]:
                batting.score += 1
                continue

            else:
                runs = int(ball)
                batting.score += runs
                striker.runs += runs
                striker.balls += 1
                bowler.runs_conceded += runs

                if runs % 2 == 1:
                    striker, non_striker = non_striker, striker

            balls += 1

            if balls % 6 == 0:
                striker, non_striker = non_striker, striker

        return batting.score

    def start(self):
        print(f"\n🆔 Match ID: {self.match_id}")

        target = self.play(self.teamA, self.teamB, 1) + 1
        print(f"\n🎯 Target: {target}")

        score2 = self.play(self.teamB, self.teamA, 2)

        if score2 >= target:
            print(f"\n🎉 {self.teamB.name} WON!")
            self.winner = self.teamB.name
        else:
            print(f"\n🏆 {self.teamA.name} WON!")
            self.winner = self.teamA.name

        # SAVE
        save_all(self)

        # SHOW SUMMARY 🔥
        show_match_summary(self)


# ---------------- RUN ----------------
os.makedirs("artifacts", exist_ok=True)

teamA_name = input("Enter Team A: ")
teamB_name = input("Enter Team B: ")

overs = int(input("Enter overs (2/20/50): "))

teamA = Team(teamA_name)
teamB = Team(teamB_name)

match = Match(teamA, teamB, overs)
match.start()

In [ ]:
def show_match_summary(match):

    print("\n" + "="*40)
    print("🏏 MATCH SUMMARY")
    print("="*40)

    print(f"\n{match.teamA.name}: {match.teamA.score}/{match.teamA.wickets}")
    print(f"{match.teamB.name}: {match.teamB.score}/{match.teamB.wickets}")

    print(f"\n🏆 Winner: {match.winner}")

    # -------- TOP BATSMAN --------
    all_players = match.teamA.players + match.teamB.players

    top_batsman = max(all_players, key=lambda x: x.runs)
    print(f"\n🔥 Top Batsman: {top_batsman.name} ({top_batsman.runs} runs)")

    # -------- TOP BOWLER --------
    top_bowler = max(all_players, key=lambda x: x.wickets)
    print(f"🎯 Top Bowler: {top_bowler.name} ({top_bowler.wickets} wickets)")

    print("="*40)

In [ ]:
show_match_summary(match)

In [ ]:

# Load dataset
df = pd.read_csv("../artifacts/Ground_clean_dataset.csv")

# Load trained ML components
rf_model = joblib.load("../artifacts/rf_model.joblib")
scaler = joblib.load("../artifacts/scaler.joblib")
model_features = joblib.load("../artifacts/model_features1.joblib")

print("Dataset and model loaded successfully")

In [ ]:
# Columns used in training
yes_no_cols = ["Lights", "Parking", "Washrooms", "Pavilion", "Scoreboard"]
numeric_cols = ["Length", "Width", "Rooms", "Parking Cap.", "Price (LKR)", "Rating"]
categorical_cols = ["City", "District", "Province", "Ground Type", "Pitch"]

# Pre-calc medians & modes
num_medians = {col: df[col].median() for col in numeric_cols}
cat_modes = {col: df[col].mode()[0] for col in categorical_cols}

print("Helper stats ready")

### normal Ground Search

In [ ]:
def search_grounds(
    city=None,
    district=None,
    province=None,
    ground_type=None,
    pitch=None,
    needs_lights=None,
    needs_parking=None,
    max_price=None
):

    results = df.copy()

    # Normalize text inputs to lowercase 
    city_l        = city.lower().strip()        if city else None
    district_l    = district.lower().strip()    if district else None
    province_l    = province.lower().strip()    if province else None
    ground_type_l = ground_type.lower().strip() if ground_type else None
    pitch_l       = pitch.lower().strip()       if pitch else None

    if city_l:
        results = results[results["City"].str.lower() == city_l]

    if district_l:
        results = results[results["District"].str.lower() == district_l]

    if province_l:
        results = results[results["Province"].str.lower() == province_l]

    if ground_type_l:
        results = results[results["Ground Type"].str.lower() == ground_type_l]

    if pitch_l:
        results = results[results["Pitch"].str.lower() == pitch_l]

    if needs_lights is not None:
        results = results[results["Lights"] == ("Yes" if needs_lights else "No")]

    if needs_parking is not None:
        results = results[results["Parking"] == ("Yes" if needs_parking else "No")]

    if max_price is not None:
        results = results[results["Price (LKR)"] <= max_price]

    if results.empty:
        print("No grounds found for these filters.")
        return

    cols_to_show = [
        "Ground Name",
        "City",
        "District",
        "Province",
        "Ground Type",
        "Pitch",
        "Lights",
        "Parking",
        "Price (LKR)",
        "Rooms",
        "Rating"
    ]
    return results[cols_to_show]

In [ ]:
search_grounds(city="colombo")

In [ ]:
search_grounds(
    province="Western",
    pitch="turf",
    needs_lights=True,
    max_price=150000
)

In [ ]:
search_grounds(city="colombo")

In [ ]:
search_grounds(city="Piliyandala")

### ML-based Recommendation

In [ ]:
def recommend_grounds(
    city=None,
    district=None,
    province=None,
    ground_type=None,
    pitch=None,
    needs_lights=None,
    needs_parking=None,
    max_price=None,
    top_n=5
):
    subset = df.copy()

    # Normalize text inputs
    city_l        = city.lower().strip()        if city else None
    district_l    = district.lower().strip()    if district else None
    province_l    = province.lower().strip()   if province else None
    ground_type_l = ground_type.lower().strip() if ground_type else None
    pitch_l       = pitch.lower().strip()       if pitch else None

    # Apply filters
    if city_l:
        subset = subset[subset["City"].str.lower() == city_l]

    if district_l:
        subset = subset[subset["District"].str.lower() == district_l]

    if province_l:
        subset = subset[subset["Province"].str.lower() == province_l]

    if ground_type_l:
        subset = subset[subset["Ground Type"].str.lower() == ground_type_l]

    if pitch_l:
        subset = subset[subset["Pitch"].str.lower() == pitch_l]

    if needs_lights is not None:
        subset = subset[subset["Lights"] == ("Yes" if needs_lights else "No")]

    if needs_parking is not None:
        subset = subset[subset["Parking"] == ("Yes" if needs_parking else "No")]

    if max_price is not None:
        subset = subset[subset["Price (LKR)"] <= max_price]

    if subset.empty:
        print("No grounds match these filters.")
        return

    # Preprocess for model
    temp = subset.copy()
    temp = temp.drop(columns=["Ground Name"])

    for col in yes_no_cols:
        temp[col] = temp[col].map({"Yes": 1, "No": 0})

    for col in numeric_cols:
        temp[col] = temp[col].fillna(num_medians[col])

    for col in categorical_cols:
        temp[col] = temp[col].fillna(cat_modes[col])

    temp_encoded = pd.get_dummies(temp, columns=categorical_cols, drop_first=True)
    temp_encoded = temp_encoded.reindex(columns=model_features, fill_value=0)

    temp_scaled = scaler.transform(temp_encoded)

    scores = rf_model.predict_proba(temp_scaled)[:, 1]

    subset["score"] = scores
    subset = subset.sort_values(by="score", ascending=False)

    return subset.head(top_n)

In [ ]:
recommend_grounds(
    province="Western",
    pitch="matting",
    max_price=80000,
    top_n=5
)

In [ ]:
recommend_grounds(
    ground_type="Public",
    needs_lights=True,
    needs_parking=True,
    top_n=10
)

In [ ]:
df_raw.head()